const products = [
    { 
        id: 1, 
        name: "Chompa Clásica Verde", 
        description: "Tejido grueso ideal para invierno, con cuello redondo.",
        price: 250, 
        category: "Ropa",
        target: "Hombre", 
        size: "L", 
        colors: ["#3E5A44", "#2A2A2A"],
        isNew: true,
        isBestSeller: true,
        image: "assets/images/adults.png" 
    },
    { 
        id: 2, 
        name: "Suéter Marfil Cálido", 
        description: "Diseño elegante en tonos neutros, perfecto para cualquier ocasión.",
        price: 280, 
        category: "Ropa",
        target: "Mujer", 
        size: "M", 
        colors: ["#F9F8F6", "#8B7355"],
        isNew: false,
        isBestSeller: true,
        image: "assets/images/editorial.png" 
    },
    { 
        id: 3, 
        name: "Chompa Bebé Verde", 
        description: "Lana extra suave diseñada para cuidar la piel de tu bebé.",
        price: 120, 
        category: "Ropa",
        target: "Bebés", 
        size: "S", 
        colors: ["#3E5A44"],
        isNew: true,
        isBestSeller: false,
        image: "assets/images/kids.png" 
    },
    { 
        id: 4, 
        name: "Poncho Andino Marfil", 
        description: "Herencia cultural en un diseño contemporáneo.",
        price: 350, 
        category: "Ropa",
        target: "Mujer", 
        size: "U", 
        colors: ["#F9F8F6", "#3E5A44"],
        isNew: false,
        isBestSeller: true,
        image: "assets/images/adults.png" 
    },
    { 
        id: 5, 
        name: "Gorro y Bufanda Bebé", 
        description: "Conjunto indispensable para protegerlos del frío.",
        price: 90, 
        category: "Accesorios",
        target: "Bebés", 
        size: "U", 
        colors: ["#8B7355"],
        isNew: false,
        isBestSeller: true,
        image: "assets/images/kids.png" 
    },
    { 
        id: 6, 
        name: "Suéter Tejido a Mano", 
        description: "Edición especial con texturas únicas.",
        price: 400, 
        category: "Ropa",
        target: "Hombre", 
        size: "XL", 
        colors: ["#2A2A2A", "#8B7355"],
        isNew: true,
        isBestSeller: false,
        image: "assets/images/texture.png" 
    },
    { 
        id: 7, 
        name: "Cardigan Otoño", 
        description: "Abertura frontal con botones de madera tallada.",
        price: 320, 
        category: "Ropa",
        target: "Mujer", 
        size: "M", 
        colors: ["#8B7355"],
        isNew: true,
        isBestSeller: false,
        image: "assets/images/editorial.png" 
    },
    { 
        id: 8, 
        name: "Guantes de Lana Pura", 
        description: "Flexibilidad y calidez en cada movimiento.",
        price: 75, 
        category: "Accesorios",
        target: "Hombre", 
        size: "U", 
        colors: ["#2A2A2A"],
        isNew: false,
        isBestSeller: false,
        image: "assets/images/process.png" 
    },
    { 
        id: 9, 
        name: "Suéter Niños Aventura", 
        description: "Resistente y cómodo para sus días de juego.",
        price: 150, 
        category: "Ropa",
        target: "Niños", 
        size: "M", 
        colors: ["#3E5A44", "#F9F8F6"],
        isNew: false,
        isBestSeller: true,
        image: "assets/images/kids.png" 
    },
    { 
        id: 10, 
        name: "Chaleco Premium", 
        description: "Corte clásico ideal para combinar con camisas.",
        price: 210, 
        category: "Ropa",
        target: "Hombre", 
        size: "L", 
        colors: ["#2A2A2A"],
        isNew: true,
        isBestSeller: false,
        image: "assets/images/adults.png" 
    },
    { 
        id: 11, 
        name: "Bufanda Infinita", 
        description: "Vueltas de pura suavidad para días helados.",
        price: 110, 
        category: "Accesorios",
        target: "Mujer", 
        size: "U", 
        colors: ["#F9F8F6", "#8B7355"],
        isNew: false,
        isBestSeller: true,
        image: "assets/images/texture.png" 
    },
    { 
        id: 12, 
        name: "Gorro Invierno Clásico", 
        description: "Tejido en punto elástico que se adapta perfectamente.",
        price: 65, 
        category: "Accesorios",
        target: "Hombre", 
        size: "U", 
        colors: ["#3E5A44"],
        isNew: true,
        isBestSeller: false,
        image: "assets/images/adults.png" 
    }
];
